set( ZLIB_INCLUDE_DIR ${CUL_DEPS_PATH}/zlib )

set( ZLIB_ADDITIONAL_INCLUDE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CUL_RENEGATE_DIR}/deps/zlib )

list( APPEND ZLIB_INCLUDE_DIR ${ZLIB_ADDITIONAL_INCLUDE} )

set( ZLIB_LIBRARY zlibstatic )
set( ZLIB_FOUND true )