# Only for multi-config generators (Visual Studio)
if(CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_CONFIGURATION_TYPES
        Debug
        Test
        Release
        CACHE STRING "" FORCE)
endif()

# Test inherits RelWithDebInfo
set(CMAKE_C_FLAGS_TEST "${CMAKE_C_FLAGS_RELWITHDEBINFO}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_TEST "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}" CACHE STRING "" FORCE)

set(CMAKE_EXE_LINKER_FLAGS_TEST
    "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}"
    CACHE STRING "" FORCE)

set(CMAKE_SHARED_LINKER_FLAGS_TEST
    "${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}"
    CACHE STRING "" FORCE)