if( NOT DEFINED ENV{CUL_ROOT_DIR} )
    message(FATAL_ERROR "[Findglm.cmake] ENV{CUL_ROOT_DIR} is not set.")
endif( NOT DEFINED ENV{CUL_ROOT_DIR} )
set( glm_ROOT_DIR $ENV{CUL_ROOT_DIR}/deps/glm )
set( glm_INCLUDE_DIR ${glm_ROOT_DIR} )
set( glm_FOUND true )
